---
- include_tasks:        '../tasks/install_packages.yml'
- include_tasks:        '../tasks/copy_remote_files.yml'
- include_tasks:        '../tasks/enable_services.yml'
- include_tasks:        '../tasks/reboot.yml'
  when:                 install_packages_result.changed or copy_remote_files_result.changed
- include_tasks:        '../tasks/apt_purge_packages.yml'
- include_tasks:        '../tasks/install_files.yml'
